### PR TITLE
Delegate password hashing to ppolicy

### PR DESCRIPTION
**Pull request by HaithemSouala**

### CODE REVIEW

**Comment by fdaugan** [comment]
With this new implementation, ppolicy becomes mandatory otherwise clear password is stored and also implies a synchronized release on both sides. A flag should be added to pick the digest CLEAR (and maybe) or SSHA.

**Comment by HaithemSouala** [comment]
Something like that : service:id :ldap:hash-clear-password=[TRUE|FALSE]
* FALSE: clear password passed to LDAP (and depend if ppolicy is configured to hash the password or not)
* TRUE:  hashing password using the ligoj function UserLdapRepository#digest(String password)

**Comment by fdaugan** [comment]
"hash-clear-password" must be enabled by default. 
Also, it uses 2 antinomic words, and  should be:
- Either a digest enabled mode message like: "hash-password" or "digest-password". Default value is "true"
- (preferred) Either a disabled mode message like: "overlay-password" or "clear-password". Default value is "false"

**Comment by HaithemSouala** [comment]
The seconde suggestion was implemented and all checks passed.

**Pull request merged**
